const initialBoardMock = [
  [
    { color: "BLACK", symbol: "R", chessPosition: { row: "a", column: 8 } },
    { color: "BLACK", symbol: "N", chessPosition: { row: "b", column: 8 } },
    { color: "BLACK", symbol: "B", chessPosition: { row: "c", column: 8 } },
    { color: "BLACK", symbol: "Q", chessPosition: { row: "d", column: 8 } },
    { color: "BLACK", symbol: "K", chessPosition: { row: "e", column: 8 } },
    { color: "BLACK", symbol: "B", chessPosition: { row: "f", column: 8 } },
    { color: "BLACK", symbol: "N", chessPosition: { row: "g", column: 8 } },
    { color: "BLACK", symbol: "R", chessPosition: { row: "h", column: 8 } },
  ],
  [
    { color: "BLACK", symbol: "P", chessPosition: { row: "a", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "b", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "c", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "d", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "e", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "f", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "g", column: 7 } },
    { color: "BLACK", symbol: "P", chessPosition: { row: "h", column: 7 } },
  ],
  [
    { chessPosition: { row: "a", column: 6 } },
    { chessPosition: { row: "b", column: 6 } },
    { chessPosition: { row: "c", column: 6 } },
    { chessPosition: { row: "d", column: 6 } },
    { chessPosition: { row: "e", column: 6 } },
    { chessPosition: { row: "f", column: 6 } },
    { chessPosition: { row: "g", column: 6 } },
    { chessPosition: { row: "h", column: 6 } },
  ],
  [
    { chessPosition: { row: "a", column: 5 } },
    { chessPosition: { row: "b", column: 5 } },
    { chessPosition: { row: "c", column: 5 } },
    { chessPosition: { row: "d", column: 5 } },
    { chessPosition: { row: "e", column: 5 } },
    { chessPosition: { row: "f", column: 5 } },
    { chessPosition: { row: "g", column: 5 } },
    { chessPosition: { row: "h", column: 5 } },
  ],
  [
    { chessPosition: { row: "a", column: 4 } },
    { chessPosition: { row: "b", column: 4 } },
    { chessPosition: { row: "c", column: 4 } },
    { chessPosition: { row: "d", column: 4 } },
    { chessPosition: { row: "e", column: 4 } },
    { chessPosition: { row: "f", column: 4 } },
    { chessPosition: { row: "g", column: 4 } },
    { chessPosition: { row: "h", column: 4 } },
  ],
  [
    { chessPosition: { row: "a", column: 3 } },
    { chessPosition: { row: "b", column: 3 } },
    { chessPosition: { row: "c", column: 3 } },
    { chessPosition: { row: "d", column: 3 } },
    { chessPosition: { row: "e", column: 3 } },
    { chessPosition: { row: "f", column: 3 } },
    { chessPosition: { row: "g", column: 3 } },
    { chessPosition: { row: "h", column: 3 } },
  ],
  [
    { color: "WHITE", symbol: "P", chessPosition: { row: "a", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "b", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "c", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "d", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "e", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "f", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "g", column: 2 } },
    { color: "WHITE", symbol: "P", chessPosition: { row: "h", column: 2 } },
  ],
  [
    { color: "WHITE", symbol: "R", chessPosition: { row: "a", column: 1 } },
    { color: "WHITE", symbol: "N", chessPosition: { row: "b", column: 1 } },
    { color: "WHITE", symbol: "B", chessPosition: { row: "c", column: 1 } },
    { color: "WHITE", symbol: "Q", chessPosition: { row: "d", column: 1 } },
    { color: "WHITE", symbol: "K", chessPosition: { row: "e", column: 1 } },
    { color: "WHITE", symbol: "B", chessPosition: { row: "f", column: 1 } },
    { color: "WHITE", symbol: "N", chessPosition: { row: "g", column: 1 } },
    { color: "WHITE", symbol: "R", chessPosition: { row: "h", column: 1 } },
  ],
];

export default initialBoardMock;
